import type { WorkObj } from ".";

export const sortedWorksData: WorkObj[] = [
  {
    id: "1a2b3c4d5e6f7g8h9i",
    title: "Portfolio Website",
    description: "A personal portfolio built with Next.js and Tailwind CSS.",
    body: "This portfolio showcases various web development projects, including frontend and backend work, built using modern technologies such as React, Next.js, and Tailwind CSS. It also integrates with a CMS for easy content management.",
    tags: ["Next.js", "Tailwind", "Portfolio"],
    image: "https://picsum.photos",
    url: "https://example.com/portfolio",
  },
  {
    id: "2b3c4d5e6f7g8h9i1a",
    title: "E-commerce Platform",
    description: "An online shop application using React and Stripe.",
    body: "A fully functional e-commerce platform that supports product listings, shopping cart, and secure Stripe payments. Includes admin dashboard for managing inventory and orders.",
    tags: ["React", "Stripe", "E-commerce"],
    image: "https://picsum.photos",
    url: "https://example.com/shop",
  },
  {
    id: "3c4d5e6f7g8h9i1a2b",
    title: "Blog CMS",
    description: "Custom CMS for a developer blog.",
    body: "A headless CMS built using Sanity.io and integrated with Next.js frontend. Includes markdown support, author profiles, and live preview editing.",
    tags: ["Next.js", "Sanity", "CMS"],
    image: "https://picsum.photos",
    url: "https://example.com/blog",
  },
  {
    id: "4d5e6f7g8h9i1a2b3c",
    title: "Task Management App",
    description: "Trello-like task board for teams.",
    body: "A task management app featuring drag-and-drop Kanban boards, team collaboration, real-time updates via WebSockets, and dark mode support.",
    tags: ["React", "Firebase", "Real-time"],
    image: "https://picsum.photos",
    url: "https://example.com/tasks",
  },
  {
    id: "5e6f7g8h9i1a2b3c4d",
    title: "Weather Dashboard",
    description: "Weather forecast app using OpenWeatherMap API.",
    body: "Provides real-time weather data with location-based search, 7-day forecast, and beautiful weather icons using OpenWeatherMap API and Chart.js.",
    tags: ["API", "Chart.js", "Weather"],
    image: "https://picsum.photos",
    url: "https://example.com/weather",
  },
  {
    id: "6f7g8h9i1a2b3c4d5e",
    title: "Chat Application",
    description: "Real-time chat with rooms and authentication.",
    body: "A secure chat app featuring multiple rooms, Google authentication, real-time messaging using Socket.IO, and a responsive UI built with Tailwind.",
    tags: ["Socket.IO", "Firebase", "Chat"],
    image: "https://picsum.photos",
    url: "https://example.com/chat",
  },
  {
    id: "7g8h9i1a2b3c4d5e6f",
    title: "Recipe Finder",
    description: "Search recipes by ingredients using Edamam API.",
    body: "Users can enter ingredients to find relevant recipes, complete with calorie counts and health labels. Includes filter options and favorites.",
    tags: ["API", "Edamam", "Search"],
    image: "https://picsum.photos",
    url: "https://example.com/recipes",
  },
  {
    id: "8h9i1a2b3c4d5e6f7g",
    title: "Fitness Tracker",
    description: "Track workouts and goals with charts.",
    body: "Allows users to log workouts, track progress with graphs, and set goals. Built using React, Redux, and Chart.js for visual insights.",
    tags: ["React", "Redux", "Fitness"],
    image: "https://picsum.photos",
    url: "https://example.com/fitness",
  },
  {
    id: "9i1a2b3c4d5e6f7g8h",
    title: "URL Shortener",
    description: "A simple tool to shorten long URLs.",
    body: "Custom-built URL shortener with analytics dashboard. Users can see click stats, expiration dates, and create custom short links.",
    tags: ["Node.js", "MongoDB", "URL"],
    image: "https://picsum.photos",
    url: "https://example.com/shorten",
  },
  {
    id: "1a2b3c4d5e6f7g8h9z",
    title: "Markdown Editor",
    description: "Live preview markdown writing app.",
    body: "A markdown editor with live preview, syntax highlighting, and export to PDF feature. Built using React and simplemde.",
    tags: ["Markdown", "Editor", "React"],
    image: "https://picsum.photos",
    url: "https://example.com/editor",
  },
  {
    id: "2b3c4d5e6f7g8h9z1a",
    title: "Language Learning App",
    description: "Gamified vocabulary learning.",
    body: "A flashcard-based app for learning new vocabulary, with spaced repetition, progress tracking, and mini-games to make learning fun.",
    tags: ["Language", "Gamification", "Education"],
    image: "https://picsum.photos",
    url: "https://example.com/learn",
  },
  {
    id: "3c4d5e6f7g8h9z1a2b",
    title: "Finance Tracker",
    description: "Personal finance and expense manager.",
    body: "A budgeting tool to track income and expenses, categorize spending, and generate monthly reports with charts and export options.",
    tags: ["Finance", "Budgeting", "Charts"],
    image: "https://picsum.photos",
    url: "https://example.com/finance",
  },
];
